name: Python Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest numpy torch tensorflow
          pip freeze # Lists installed packages for debugging

      - name: Run tests
        run: |
          pytest

      # Optional: Add a step to explicitly list TensorFlow installation
      - name: Verify TensorFlow Installation
        run: |
          python -c "import tensorflow as tf; print(tf.__version__)"
